trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

stages:
  # - stage: BuildMaven
  #   jobs:
  #     - job: Build
  #       displayName: Build Maven
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #         - checkout: self
  #         - task: Maven@3
  #           inputs:
  #             mavenPomFile: 'pom.xml'
  #             goals: 'clean install'

  #         - script: |
  #             docker build -t mahec/devops-integration .
  #           displayName: Build Docker Image

  #         - script: |
  #             docker login -u mahec -p mahesh3@AM
  #             docker push mahec/devops-integration
  #           displayName: Push Docker Image


  # - stage: Dependencycheck
  #   jobs:
  #     - job: DependencyCheck
  #       displayName: Dependency check
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #         - checkout: self
  #         - script: mvn org.owasp:dependency-check-maven:8.0.0:purge
  #           displayName: 'Dependency Check'

  # - stage: Builddockerimage
  #   dependsOn: BuildMaven
  #   jobs:
  #     - job: BuildDockerImage
  #       displayName: Build docker image
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #         - script: |
  #             docker build -t mahec/devops-integration .
  #           displayName: Build Docker Image

  # - stage: PushimagetoHub
  #   dependsOn: Builddockerimage
  #   jobs:
  #     - job: PushImageToHub
  #       displayName: Push image to Hub
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #         - script: |
  #             docker login -u mahec -p mahesh3@AM
  #             docker push mahec/devops-integration
  #           displayName: Push Docker Image

  - stage: SnykCodeScan
    jobs:
      - job: SnykCodeScan
        displayName: Snyk Code Scan
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              snyk auth 0449b11d-9608-452e-8c8b-f6a13282af9f
              npx snyk test --all-projects
            displayName: Snyk Code Scan

  - stage: SonarCloudCodeAnalysis
    jobs:
      - job: SonarCloudCodeAnalysis
        displayName: SonarCloud Code Analysis
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: SonarQubePrepare@4
            inputs:
              SonarQube: 'sonarcloud'
              scannerMode: 'MSBuild'

          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'sonar:sonar'
