trigger:
  branches:
    include:
      - test

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Checkout
  displayName: 'Checkout Source Code'
  jobs:
  - job: Checkout
    displayName: 'Checkout'
    steps:
    - checkout: self
      submodules: true

- stage: BuildAndContainerize
  displayName: 'Build'
  jobs:
  - job: BuildAndContainerize
    displayName: 'Build Maven Project'
    steps:
    - task: Maven@3
      displayName: 'Maven Build'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
    - task: Docker@2
      displayName: 'Build and Push Image'
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'mahec/new'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

# - stage: Containerize
#   displayName: 'Containerize'
#   jobs:
#   - job: Containerize
#     displayName: 'Build and Push Docker Image'
#     steps:
#     - task: Docker@2
#       displayName: 'Build and Push Image'
#       inputs:
#         containerRegistry: 'DockerHub'
#         repository: 'mahec/new'
#         command: 'buildAndPush'
#         dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

- stage: DependencyCheck
  displayName: 'Dependency Check'
  jobs:
  - job: DependencyCheck
    displayName: 'Run Dependency Check'
    steps:
    - task: Maven@3
      displayName: 'Dependency Check'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'dependency:analyze'
        publishJUnitResults: true

- stage: SnykCodeScan
  displayName: 'Snyk Code Scanning'
  jobs:
  - job: SnykCodeScan
    displayName: 'Run Snyk Code Scan'
    steps:
    - script: |
        chmod +x mvnw
        npm install -g snyk
        snyk auth 0449b11d-9608-452e-8c8b-f6a13282af9f
        snyk test --all-projects -d || echo "Snyk scan encountered vulnerabilities, but the workflow will continue."
      displayName: 'Snyk Code Scan'

- stage: SonarCloudCodeAnalysis
  displayName: 'SonarCloud Code Analysis'
  jobs:
  - job: SonarCloudCodeAnalysis
    displayName: 'Run SonarCloud Code Analysis'
    steps:
    - task: SonarCloudPrepare@1
      displayName: 'Prepare SonarCloud Analysis'
      inputs:
        SonarCloud: 'sonarcloud'
        organization: 'sonartest333'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'sonartest333'
        cliProjectName: 'sonartest333'
        cliSources: '$(Build.SourcesDirectory)'
    - task: SonarCloudAnalyze@1
      displayName: 'Run SonarCloud Analysis'
    - task: SonarCloudPublish@1
      displayName: 'Publish SonarCloud Results'
      inputs:
        pollingTimeoutSec: '300'