on:
  push:
    branches:
      - main
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build and test
        run: |
          mvn clean install --batch-mode --no-transfer-progress 

      - name: Run SonarCloud
        run: mvn clean install sonar:sonar \
            -Dsonar.organization=Mahesh333-C \
            -Dsonar.login=SONAR_TOKEN

      - name: Run Snyk
        run: npx snyk test --all-projects --all-sub-projects --org=my-org
        
    # steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2
    
    # - name: Set up JDK
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: '11'
    #     distribution: 'adopt'
    
    # - name: Build Maven
    #   run: mvn clean install
    
    # - name: Build docker image
    #   run: |
    #     docker build -t mahec/devops-integration .
    
    # - name: Push image to Hub
    #   env:
    #     DOCKER_HUB_CREDENTIALS: ${{ secrets.DOCKERHUBPWD }}
    #   run: |
    #     echo "${DOCKER_HUB_CREDENTIALS}" | docker login -u mahec --password-stdin
    #     docker tag mahec/devops-integration docker.io/mahec/demo
    #     docker push mahec/demo
