on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Build Maven
      run: mvn clean install
    
    - name: Build docker image
      run: |
        docker build -t mahec/devops-integration .
    
    - name: Push image to Hub
      env:
        DOCKER_HUB_CREDENTIALS: ${{ secrets.DOCKERHUBPWD }}
      run: |
        echo "${DOCKER_HUB_CREDENTIALS}" | docker login -u mahec --password-stdin
        docker tag mahec/devops-integration docker.io/mahec/demo
        docker push mahec/demo
